name: Build, Push, and Deploy IRIS API

on:
  push:
    branches:
      - week_6

env:
  PROJECT_ID: mlops-iitmadras       
  REGION: us-central1                   
  GAR_REPO: iris-repo                   
  IMAGE_NAME: iris-api
  CLUSTER_NAME: iris-api-cluster    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    # Authenticate to GCP
    - name: Auth to GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    # Download MLflow Model
    - name: Setup Python & Download Model
      run: |
        pip install -r requirements.txt
        export MLFLOW_TRACKING_URI="sqlite:///mlflow.db"
        mlflow artifacts download -u models:/Iris-DecisionTree/latest -d ./model_dir

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    # Build and Push Docker Image
    - name: Build and Push Image
      run: |
        IMAGE_URI=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    # Deploy to GKE
    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        location: ${{ env.REGION }}

    - name: Deploy to Kubernetes
      run: |
        # Apply the Service to create the LoadBalancer
        kubectl apply -f k8s/service.yaml
        
        # Apply the Deployment
        kubectl apply -f k8s/deployment.yaml
        
        # Inject the newly built image tag into the deployment
        kubectl set image deployment/iris-api-deployment iris-api=${{ env.IMAGE_URI }}
        
        # Wait for the rollout to finish
        kubectl rollout status deployment/iris-api-deployment
